### ISSUE TITLE
Can not locate "killMS.killms-cohjones.sols.parset"

### ISSUE THREAD

**Issue by MziyandaAstro** [saopicc/killMS#14]
Hi,

I'm running killms and it seems that it can not locate the file "killMS.killms-cohjones.sols.parset". Help please.

[slurm_KILMS849.log](https://github.com/saopicc/killMS/files/8384485/slurm_KILMS849.log)

**Comment by cyriltasse** [comment]
Weird - maybe remlated to slurm - I don't know... 

Maybe try to give the absolute path of your ms and make sur you have permission there (cos it will try to write the calibrations solutions there). If you don't have the write permission, set `SolsDir` to somewhere you can write in

**Comment by MziyandaAstro** [comment]
I followed all your instructions and what I'm finding out is that kMS.py for some reason is detecting my /data directory as read-only and it is not. It's my working directory, I read and write stuff there al the time.

[slurm_KILMS849.log](https://github.com/saopicc/killMS/files/8387347/slurm_KILMS849.log)

**Comment by cyriltasse** [comment]
You should dig on slurm maybe? I have no knowledge on it, and how things are run through it... Maybe when python script are executed by slurm, they are not executed executed by you but by a slurm_user or so who has no write permission? Something like that? The good news is that you're getting close! :) What happen is you run kMS directly within a bash terminal?

**Comment by mattyowl** [comment]
Slurm jobs are executed as the regular user, so far as I know. I think this is something to do with running killms via singularity.

**Comment by MziyandaAstro** [comment]
Yes you're right Matt, I got this issue fixed by binding (--bind /data/mziyanda) to the correct directory.
